version: "3.8"

services:
  moodle:
    image: bitnami/moodle:3.11.8
    ports:
      - "8080:80"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_PASSWORD=moodle_password
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123
      - MOODLE_EMAIL=tu_email@gmail.com
    volumes:
      - moodle_data:/bitnami/moodle
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: bitnami/mariadb:10.5
    environment:
      - MARIADB_ROOT_PASSWORD=root123
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_USER=moodle_user
      - MARIADB_PASSWORD=moodle_password
    volumes:
      - mariadb_data:/bitnami/mariadb
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=root123",
        ]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  moodle_data:
  mariadb_data:
